language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - xvfb
    - vnc-java
    - vnc-server
    - x11vnc
    - tightvncserver
env:
  - DSPLAY=:0
before_install:
  - pip install codecov
after_success:
  - codecov
